---
- name: Install and start Apache2
  hosts: all
  become: yes
  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes

    - name: Install Apache2 package
      ansible.builtin.apt:
        name: apache2
        state: present

    - name: Start and enable Apache2 service
      ansible.builtin.systemd:
        name: apache2
        state: started
        enabled: yes
