---
- name: Ensure Apache is running
  hosts: all
  become: yes
  tasks:
    - name: Check Apache service status
      ansible.builtin.systemd:
        name: apache2
        state: started
        enabled: yes
